### ISSUE TITLE
handy tool, may be we need some documents.

### ISSUE THREAD

**Issue by secwang** [openresty/opsboy#2]

**Comment by agentzh** [comment]
Mind to create a pull request to add some docs for us? ;)

**Comment by secwang** [comment]
sure , I'm trying , may need some time.

**Comment by agentzh** [comment]
Cool, thanks a lot!

**Comment by thibaultcha** [comment]
Documentation now exists here: http://openresty.org/en/ec2-test-cluster.html Closing this :)
